HTTP/1.1 404 Not Found
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<!DOCTYPE html>
<html>
   <body>
      <h1>404 Not Found</h1>
      <p>You should be seeing this page if the Handle server was unable to resolve the RAiD</p>
   </body>
</html>