services:
  haproxy:
    image: ghcr.io/haproxytech/haproxy-docker-alpine:3.2.4
    restart: unless-stopped
    volumes:
      - ./ha-proxy-config:/usr/local/etc/haproxy/:ro
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.raid.entrypoints=websecure"
      - "traefik.http.routers.raid.rule=Host(`raid.matthias.haus`)"
      - "traefik.http.services.raid.loadbalancer.server.port=80"
      - "traefik.http.routers.raid.middlewares=security@docker"
      - wud.tag.include=^\d+\.\d+\.\d+$$
      - wud.link.template=https://github.com/haproxy/haproxy/releases/tag/v$${major}.$${minor}.$${patch}

networks:
  web:
    external: true