services:
  haproxy:
    image: ghcr.io/haproxytech/haproxy-docker-alpine:3.2.4
    restart: unless-stopped
    volumes:
      - ./ha-proxy-config:/usr/local/etc/haproxy/:ro
    ports:
      - 8080:80
